on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn global add react-static && yarn add @babel/runtime
      - name: Build
        run: yarn build
        env:
          SENDINBLUE_API_KEY: ${{secrets.SENDINBLUE_API_KEY}}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
